dependencies:
  - openmc >= 0.13.3
  - multipledispatch
  - distributed
  - numpy
  - matplotlib
  - cytoolz
  - xarray
  - scipy
  - pandas
  - ramp-coremaker
  - ramp-corecompute
  - python < 3.14

